### ISSUE TITLE
Go get gives me "no field or method NumInactiveChannels"

### ISSUE THREAD

**Issue by karloluiten** [LLeny/lncli-curses#1]
**Describe the bug**
If I do the first step of build, I get an error.

**To Reproduce**
1. Login to server I installed lnd on
2. As root, do `go get github.com/lleny/lncli-curses`

**Expected behavior**
Something something building ;)

**Screenshots**
```
# go get github.com/lleny/lncli-curses
# github.com/lleny/lncli-curses
gocode/src/github.com/lleny/lncli-curses/gui.go:165: status.localNodeInfo.NumInactiveChannels undefined (type lnrpc.GetInfoResponse has no field or method NumInactiveChannels)
```

**Desktop (please complete the following information):**
 Centos7

**Additional context**
None :)

**Comment by LLeny** [comment]
Try to delete the gocode/src/github.com/lightningnetwork folder and do the go get again. You may have an older version of the lnd sources.

**Comment by karloluiten** [comment]
Thank you. I tried. Not really familiar with go, sorry. I updated lnd. Then removed the github.com/llenvy directory recursively. Then I did:
```
[ ~]# go get github.com/lleny/lncli-curses
[ ~]# cd $GOPATH/src/github.com/lleny/lncli-curses
[ lncli-curses]# dep ensure
could not find project Gopkg.toml, use dep init to initiate a manifest
```
Does that ring a bell?

**Comment by LLeny** [comment]
Just try to skip the dep ensure and call just make.

**Comment by karloluiten** [comment]
Working! Thanks, this is great. It is still syncing to mainnet (from my lnd upgrade I guess), but this looks cool :+1:
